--- Magnitude Analysis

/* Measure by Dimension
Eg. Total Sales by Country
Total Quantity by Category
Average Price by Product
Total Order by Customer
*/

-- Find Total customers by Countries 
select 
    country,
	count(customer_key) as total_customer_by_country
from gold.dim_customers
group by country
order by total_customer_by_country desc;

-- Find Total customers by gender
select
    gender,
	count(customer_key) as total_customer_by_gender
from gold.dim_customers
group by gender
order by total_customer_by_gender desc;


-- Find Total products by category
select
    category,
	count(product_key) as total_product_by_category
from gold.dim_products
group by category
order by total_product_by_category desc;

-- What is the Avg cost in each category
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- What is the total revn generated for each category
select 
	p.category,
	sum (f.sales_amount) as total_revn_by_category
from gold.fact_sales f
join gold.dim_products p
on p.product_key = f.product_key 
group by p.category
order by total_revn_by_category desc;


-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;



-- What is the distribution of sold items across countries
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;